// apps/vue-app/src/App.vue
<template>
  <div id="nav">
    <p>主应用的数据: {{mainAppState ? mainAppState.name : '无'}}</p>

    <button @click="sendToMain">vue3-app => 基座</button>

    <hr>

    <header>
      <router-link to="/">Home</router-link> |
      <router-link to="/about">About</router-link>
    </header>
  </div>
  <router-view/>
</template>

<script>
export default {
  name: 'App',
  data() {
    return {
      mainAppState: window.microApp ? window.microApp.getData() : { name: '无' },
    }
  },
  mounted() {
    if (window.microApp) {
      window.microApp.addDataListener(this.dataListener)
    }
  },
  methods: {
    dataListener(data) {
      console.log('主应用的数据', data);
      this.mainAppState = data;
    },
    sendToMain() {
      window.microApp.dispatch({msg: `我是 vue3-app 随机数 ${Math.random()}`})
    }
  },
  unmounted() {
    if (window.microApp) {
      window.microApp.clearDataListener();
    }
  }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
}

#nav {
  padding: 30px;
}

#nav a {
  font-weight: bold;
  color: #2c3e50;
}

#nav a.router-link-exact-active {
  color: #42b983;
}
</style>

// apps/react-app/src/App.js
import React, {useEffect, useState} from 'react'
import {BrowserRouter, Link, Route, Routes} from "react-router-dom";
import Home from './pages/Home';
import About from './pages/About';
import styles from './styles.module.css';

function App() {
  const [mainAppData, setMainAppData] = useState( window.microApp.getData());

  useEffect(() => {
    if (window.microApp) {
      const dataListener = (data) => {
        console.log('主应用传的数据', data);
        setMainAppData(data);
      }

      window.microApp.addDataListener(dataListener)
      return () => {
        window.microApp.clearDataListener()
      }
    }
  })

  const sendToMain = () => {
    window.microApp.dispatch({msg: `我是 react-app 随机数 ${Math.random()}`})
  }

  return (
    <div>
      <p>主应用的数据：{mainAppData ? mainAppData.name : '无'}</p>

      <button onClick={sendToMain}>给基座应用发送</button>

      <BrowserRouter basename={window.__MICRO_APP_BASE_ROUTE__ || '/'}>
        <div>
          <header className={styles.header}>
            <Link to="/">react-app Home</Link>
            <Link to="/about">react-app About</Link>
          </header>

          <Routes>
            <Route path="/" element={<Home/>}/>
            <Route path="/about" element={<About/>}/>
          </Routes>
        </div>
      </BrowserRouter>
    </div>
  );
}

export default App;
